#
//  swift.yml
//  GoldenCount
//
//  Created by Muugii M. on 2/15/25.
//

name: Swift CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install SwiftLint
        run: brew install swiftlint
      
      - name: Run SwiftLint
        run: swiftlint --strict
  
  build-and-test:
    needs: lint
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app
      
      - name: Build
        run: |
          xcodebuild clean build \
            -scheme GoldenCount \
            -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=latest' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      
      - name: Test
        run: |
          xcodebuild test \
            -scheme GoldenCount \
            -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=latest' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
